import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider.jsx"; // named import
import Header from "@/components/header.jsx"; // default import
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
  

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "AI-Career Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme:dark,
    }}>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
       <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
        >
         <Header/>
          <main className="min-h-screen">
          {children}
          </main>

          <footer className="bg-muted/50 py-12 my-4">
            <div className="container mx-auto px-4 text-center text-grey-200">
              <p>
                Made with love by me 
              </p>
            </div>
            </footer>
          </ThemeProvider>
      </body>
      </html>
      </ClerkProvider>
  );
}
